// src/app/[locale]/examples/[category]/metadata.ts
import type { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';

const validCategories = ['bachelor', 'master', 'coursework'];

export async function generateMetadata({
  params: { locale, category },
}: {
  params: { locale: string; category: string };
}): Promise<Metadata> {
  console.log('🎯 Category metadata called for:', { locale, category });

  const baseUrl =
    process.env.NEXT_PUBLIC_BASE_URL || 'https://www.smart-edu.ai';

  // Sprawdź czy kategoria jest prawidłowa
  if (!validCategories.includes(category)) {
    console.log('❌ Invalid category:', category);
    return {
      title: 'Przykłady prac | Smart-Edu.ai',
      description: 'Przeglądaj przykłady prac wygenerowanych przez AI',
    };
  }

  // Pobierz tłumaczenia
  const t = await getTranslations({ locale, namespace: 'examples' });

  // Pobierz tytuł z tłumaczeń
  const workTypeName = t(`${category}.title`);
  const workTypeDescription = t(`${category}.description`);

  console.log('📝 WorkType name:', workTypeName);

  // Format: "[rodzaj pracy] - wzory, przykłady gotowe do pobrania pdf"
  const title =
    locale === 'pl'
      ? `${workTypeName} - wzory, przykłady gotowe do pobrania PDF | Smart-Edu.ai`
      : `${workTypeName} - samples, examples ready to download PDF | Smart-Edu.ai`;

  console.log('✅ Final category title:', title);

  const description =
    locale === 'pl'
      ? `${workTypeDescription}. Sprawdź gotowe wzory do pobrania w formacie PDF. Pobierz bezpłatne przykłady prac akademickich wygenerowane przez AI.`
      : `${workTypeDescription}. Check out ready samples to download in PDF format. Download free examples of academic papers generated by AI.`;

  const keywords =
    locale === 'pl'
      ? `${workTypeName}, przykłady prac, wzory prac, prace PDF, generator prac AI, przykłady prac akademickich, darmowe przykłady prac`
      : `${workTypeName}, paper examples, paper samples, papers PDF, AI paper generator, academic paper examples, free paper examples`;

  const pageUrl = `${baseUrl}/${locale}/examples/${category}`;

  return {
    metadataBase: new URL(baseUrl),
    title: title,
    description: description,
    keywords: keywords,
    authors: [{ name: 'Smart-Edu.AI' }],
    creator: 'Smart-Edu.AI',
    publisher: 'Smart-Edu.AI',
    robots: {
      index: true,
      follow: true,
    },
    openGraph: {
      title: title,
      description: description,
      url: pageUrl,
      siteName: 'Smart-Edu.AI',
      locale: locale,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: title,
      description: description,
    },
    alternates: {
      canonical: pageUrl,
      languages: {
        en: `${baseUrl}/en/examples/${category}`,
        pl: `${baseUrl}/pl/examples/${category}`,
      },
    },
  };
}
